-- ============================================================================
-- Migration 003: Capture resolution_policy in linky_versions history.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/003_resolution_policy_history.sql
--
-- Idempotent: safe to re-run.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
--
-- Context: Sprint 2 introduces `linkies.resolution_policy` (a rules-engine
-- JSON blob used by `/l/[slug]` to personalize tabs per viewer). Migration 002
-- already added the column on `linkies`; this migration mirrors it into
-- `linky_versions` so every PATCH that mutates the policy snapshots the prior
-- value alongside urls/url_metadata/title/description — keeping the
-- "history is append-only" invariant the rest of the table relies on.
-- ============================================================================

BEGIN;

-- Policy snapshot column on linky_versions. Defaults to an empty object so
-- pre-existing version rows (written before Sprint 2) have a sane value when
-- replayed. The `linkies.resolution_policy` column already carries the same
-- shape + default from migration 002.
ALTER TABLE linky_versions
  ADD COLUMN IF NOT EXISTS resolution_policy JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMIT;
