-- ============================================================================
-- Migration 004: API keys for authenticated automation.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/004_api_keys.sql
--
-- Idempotent: safe to re-run.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
--
-- Context: Sprint 2.6 adds bearer API keys so the CLI, SDK, and future MCP
-- server can authenticate as either a personal subject or an organization
-- subject without relying on a browser Clerk session.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS api_keys (
  id                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  key_prefix               TEXT NOT NULL UNIQUE,
  secret_hash              TEXT NOT NULL,
  owner_user_id            TEXT REFERENCES users(clerk_user_id) ON DELETE CASCADE,
  owner_org_id             TEXT REFERENCES organizations(clerk_org_id) ON DELETE CASCADE,
  name                     TEXT NOT NULL,
  created_by_clerk_user_id TEXT REFERENCES users(clerk_user_id) ON DELETE SET NULL,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at             TIMESTAMPTZ,
  revoked_at               TIMESTAMPTZ
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'api_keys_exactly_one_owner'
  ) THEN
    ALTER TABLE api_keys
      ADD CONSTRAINT api_keys_exactly_one_owner
      CHECK (
        (owner_user_id IS NOT NULL AND owner_org_id IS NULL) OR
        (owner_user_id IS NULL AND owner_org_id IS NOT NULL)
      );
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_api_keys_owner_user
  ON api_keys (owner_user_id)
  WHERE owner_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api_keys_owner_org
  ON api_keys (owner_org_id)
  WHERE owner_org_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api_keys_active_prefix
  ON api_keys (key_prefix)
  WHERE revoked_at IS NULL;

COMMIT;
