-- ============================================================================
-- Migration 007: per-API-key hourly rate limit.
--
-- Apply with: psql "$DATABASE_URL" -f db/migrations/007_api_key_rate_limits.sql
--
-- Idempotent: safe to re-run.
-- Do NOT edit this file after it has been applied to production. Write a new
-- migration instead.
--
-- Context: Sprint 2.8 Chunk D. Until now, API keys were unmetered except by
-- per-IP rate limiting on the public create path. A runaway LLM holding a
-- real key could hit any authed endpoint as fast as the event loop allowed.
--
-- This migration adds `rate_limit_per_hour` to every key. The enforcement
-- path (src/lib/server/api-keys.ts → authenticateApiKey) consults the
-- column on every bearer-auth pass and routes the call through the
-- existing in-memory bucket implementation with a per-key bucket name.
--
--   1000 — default. Generous enough that no legitimate agent workflow
--          ever hits it; stingy enough to catch a runaway loop within
--          seconds.
--      0 — disabled. Admin / internal keys that must never rate-limit.
--
-- We intentionally keep this in-memory rather than Redis-backed: at our
-- scale (one Vercel instance most of the time) the fragmentation across
-- instances is irrelevant. Revisit with Sprint 3 horizontal scale-out.
-- ============================================================================

BEGIN;

ALTER TABLE api_keys
  ADD COLUMN IF NOT EXISTS rate_limit_per_hour INTEGER NOT NULL DEFAULT 1000;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'api_keys_rate_limit_per_hour_nonneg'
  ) THEN
    ALTER TABLE api_keys
      ADD CONSTRAINT api_keys_rate_limit_per_hour_nonneg
      CHECK (rate_limit_per_hour >= 0);
  END IF;
END
$$;

COMMIT;
